---
version: "3.2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    hostname: zookeeper
    container_name: zookeeper
    # expose ports without publishing them to the host machine
    expose:
      - "2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka
    

  broker:
    image: confluentinc/cp-server:5.4.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    # expose ports without publishing them to the host machine
    # this is internal
    expose:
      - "19092"
    # publish ports reachable from the Docker host machine (localhost)
    # this is external
    ports:
      - "9092"
    environment:
      # parameters here:
      # https://kafka.apache.org/documentation/#configuration
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      # KAFKA_ADVERTISED_LISTENERS is a comma-separated list of listeners with their
      # host/IP and port. This is the metadata that’s passed back to clients.
      # https://www.confluent.io/blog/kafka-listeners-explained/
      # TODO: will the external be reachable from a client external to the localhost?
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:19092, EXTERNAL://IP_ADDRESS:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:9092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: "true"
      CONFLUENT_SUPPORT_CUSTOMER_ID: "anonymous"
    networks:
      - kafka

  schema_registry:
    image: confluentinc/cp-schema-registry:5.4.1
    hostname: schema_registry
    container_name: schema_registry
    depends_on:
      - zookeeper
      - broker
    # expose ports without publishing them to the host machine
    expose:
      - "8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      # zookeeper election is deprecated, use kafka instead
      # https://docs.confluent.io/current/schema_registry/installation/config.html#kafkastore-bootstrap-servers
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: INTERNAL://broker:19092 
      # Comma-separated list of listeners that listen for API requests over
      # either HTTP or HTTPS. If a listener uses HTTPS, the appropriate SSL
      # configuration parameters need to be set as well.
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081" 
      DEBUG: "true"
    networks:
      - kafka

#  producer:
#    build: ./producer
#    depends_on:
#      - zookeeper
#      - broker
#      - schema_registry
#    environment: 
#      BROKER: "broker:9092"
#      #SCHEMA_REGISTRY_URL: "http://schema_registry:8081"
#    networks:
#      - kafka

networks:
  kafka:
    # bridge is the default
    driver: bridge 